/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author nebra
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnActuaData = new javax.swing.JButton();
        btnApertura = new javax.swing.JButton();
        btnRDepositos = new javax.swing.JButton();
        btnRRetiros = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("POR FAVOR SELECIONA LA OPCIÓN QUE DESEAS REALIZAR");

        btnRegistro.setText("REGISTRO DE CLIENTES");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnActuaData.setText("ACTUALIZACIÓN DE DATOS");
        btnActuaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaDataActionPerformed(evt);
            }
        });

        btnApertura.setText("APERTURA DE CUENTAS");
        btnApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAperturaActionPerformed(evt);
            }
        });

        btnRDepositos.setText("REALIZAR UN DEPOSITO");
        btnRDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRDepositosActionPerformed(evt);
            }
        });

        btnRRetiros.setText("REALIZAR UN RETIRO");
        btnRRetiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRRetirosActionPerformed(evt);
            }
        });

        btnReportes.setText("REPORTES");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnCSesion.setText("CERRAR SESIÓN");
        btnCSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnApertura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActuaData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRDepositos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRRetiros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(btnCSesion))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(btnRDepositos))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActuaData)
                    .addComponent(btnRRetiros))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApertura)
                    .addComponent(btnReportes))
                .addGap(28, 28, 28)
                .addComponent(btnCSesion)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormRegistro  registroClientes= new FormRegistro();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        registroClientes.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnActuaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaDataActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormActualizacion  ActualizacionDatos= new FormActualizacion();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        ActualizacionDatos.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnActuaDataActionPerformed

    private void btnAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAperturaActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormAperturaC  AperturaCuenta= new FormAperturaC();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        AperturaCuenta.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnAperturaActionPerformed

    private void btnRDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRDepositosActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormDepositos  Depositos= new FormDepositos();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        Depositos.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnRDepositosActionPerformed

    private void btnRRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRRetirosActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormRetiros  Retiros= new FormRetiros();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        Retiros.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnRRetirosActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        FormReportes  Reportes= new FormReportes();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        Reportes.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnCSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSesionActionPerformed
        // TODO add your handling code here:
        //PASO 1: CODIGO QUE NOS VA A PERMITIR RE DIRIGIR EL CODIGO
        Formlogin  CerrarSesion= new Formlogin();
        
        //PASO 2:HACER VISIBLE LA VARIABLE QUE YA SE CREO
        CerrarSesion.setVisible(true);
        
        // PASO 3: PARA QUE NO SE ESTEN ACUMULANDO LAS VENTANAS 
        this.dispose();
    }//GEN-LAST:event_btnCSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuaData;
    private javax.swing.JButton btnApertura;
    private javax.swing.JButton btnCSesion;
    private javax.swing.JButton btnRDepositos;
    private javax.swing.JButton btnRRetiros;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
